language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt
  - psql -c "CREATE USER malaury WITH PASSWORD 'malaury';" -U postgres

branches:
  only:
    - staging


services:
  - postgresql

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test myApp
  - ./manage.py test