language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt


branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql

script:
  - ./manage.py test