language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml



branches:
  only:
    - staging


services:
  - postgresql

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - ./manage.py test