language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt


branches:
  only:
    - staging


services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="site_reuilly.settings.travis"


script:
  - ./manage.py test