language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt
  - psql -c "CREATE USER malaury WITH PASSWORD 'malaury';" -U postgres
  - psql -c 'create database reuillytt18;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE "reuillytt18" to malaury;' -U postgres


branches:
  only:
    - staging


services:
  - postgresql

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - ./manage.py test