language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt



branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="site_reuilly.settings"

services:
  - postgresql

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - ./manage.py test