language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database test_db;' -U postgres


branches:
  only:
    - staging

env: SECRET_KEY='TEST'

services:
  - postgresql

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - ./manage.py test